#ifndef __indoors_h_INCLUDE
#define __indoors_h_INCLUDE

/*

 indoors.C

 Tile Source File.

 Info:
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to #TILECOUNT#

 Generated by Manlibear's Aseprite Map Builder

*/

/* Bank of tiles. */
#define indoorsBank 8
/* Start of tile array. */

#define indoors_length 109
#define indoors_idx 0
extern const void __bank_indoors;
extern const unsigned char indoors[];

#endif

/* End of indoors.h */