#ifndef __overworld_h_INCLUDE
#define __overworld_h_INCLUDE

/*

 overworld.C

 Tile Source File.

 Info:
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to #TILECOUNT#

 Generated by Manlibear's Aseprite Map Builder

*/

/* Bank of tiles. */
#define overworldBank 2
/* Start of tile array. */

#define overworld_length 95
#define overworld_idx 0
extern const void __bank_overworld;
extern const unsigned char overworld[];

#endif

/* End of overworld.h */