#ifndef __font_h_INCLUDE

#define __font_h_INCLUDE



/*



 font.C



 Tile Source File.



 Info:

  Format               : Gameboy 4 color.

  Compression          : None.

  Counter              : None.

  Tile size            : 8 x 8

  Tiles                : 0 to #TILECOUNT#



 Generated by Manlibear's Aseprite Map Builder



*/



/* Bank of tiles. */

#define fontBank 3

/* Start of tile array. */



#define font_length 68

#define font_idx 0

extern const void __bank_font;

extern const unsigned char font[];



#endif



/* End of font.h */