/*

 UI_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 1
   Map size      : 20 x 4
   Tile set      : ui.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 95
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __ui_map_h_INCLUDE
#define __ui_map_h_INCLUDE

#define ui_mapWidth 20
#define ui_mapHeight 4
#define ui_mapBank 4

extern const unsigned char ui_map[];

#endif

/* End of UI_MAP.H */
