/*

 UI_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 8

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __ui_tiles_h_INCLUDE
#define __ui_tiles_h_INCLUDE

/* Bank of tiles. */
#define ui_tilesBank 4
#define ui_tiles_count 9
/* Start of tile array. */
extern const void __bank_ui_tiles;
extern const unsigned char ui_tiles[];

#endif

/* End of UI_TILES.H */
