/*

 cerulean_city_map.H

 Map Include File.

 Info:
   Bank          : 1
   Map size      : 80 x 72
   Tile offset   : 104

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __cerulean_city_map_h_INCLUDE
#define __cerulean_city_map_h_INCLUDE


#define cerulean_city_map_width 80
#define cerulean_city_map_height 72
#define cerulean_city_map_bank 1
#define cerulean_city_map_offset 104

extern const unsigned char cerulean_city_map[];

#endif

/* End of cerulean_city_map.H */
