/*

 route_2_map.H

 Map Include File.

 Info:
   Bank          : 3
   Map size      : 40 x 144
   Tile offset   : 104

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __route_2_map_h_INCLUDE
#define __route_2_map_h_INCLUDE


#define route_2_map_width 40
#define route_2_map_height 144
#define route_2_map_bank 3
#define route_2_map_offset 104

extern const unsigned char route_2_map[];

#endif

/* End of route_2_map.H */
