/*

 route_4_map.H

 Map Include File.

 Info:
   Bank          : 1
   Map size      : 180 x 36
   Tile offset   : 104

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __route_4_map_h_INCLUDE
#define __route_4_map_h_INCLUDE


#define route_4_map_width 180
#define route_4_map_height 36
#define route_4_map_bank 1
#define route_4_map_offset 104

extern const unsigned char route_4_map[];

#endif

/* End of route_4_map.H */
