/*

 route_3_map.H

 Map Include File.

 Info:
   Bank          : 1
   Map size      : 140 x 36
   Tile offset   : 104

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __route_3_map_h_INCLUDE
#define __route_3_map_h_INCLUDE


#define route_3_map_width 140
#define route_3_map_height 36
#define route_3_map_bank 1
#define route_3_map_offset 104

extern const unsigned char route_3_map[];

#endif

/* End of route_3_map.H */
