/*

 route_24_map.H

 Map Include File.

 Info:
   Bank          : 1
   Map size      : 40 x 72
   Tile offset   : 104

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __route_24_map_h_INCLUDE
#define __route_24_map_h_INCLUDE


#define route_24_map_width 40
#define route_24_map_height 72
#define route_24_map_bank 1
#define route_24_map_offset 104

extern const unsigned char route_24_map[];

#endif

/* End of route_24_map.H */
