/*

 viridian_city_map.H

 Map Include File.

 Info:
   Bank          : 3
   Map size      : 80 x 72
   Tile offset   : 104

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __viridian_city_map_h_INCLUDE
#define __viridian_city_map_h_INCLUDE


#define viridian_city_map_width 80
#define viridian_city_map_height 72
#define viridian_city_map_bank 3
#define viridian_city_map_offset 104

extern const unsigned char viridian_city_map[];

#endif

/* End of viridian_city_map.H */
