#pragma bank #BANK#

/*

 #NAME#.C

 Tile Source File.

 Info:
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to #TILECOUNT#
  Bank                 : #BANK#

 Generated by Manlibear's Aseprite Map Builder

*/

/* Start of tile array. */
const void __at(#BANK#) __bank_#NAME#;
const unsigned char #NAME#[] =
{
#SPRITES#
};

/* End of #NAME#.C */
