#pragma bank #BANK#

/*

 #NAME#_map.C

 Map Source File.

 Info:
   Bank          : #BANK#
   Map size      : #WIDTH# x #HEIGHT#
   Tile offset   : #OFFSET#

 Generated by Manlibear's Aseprite Map Builder

*/

#define #NAME#_map_width #WIDTH#
#define #NAME#_map_height #HEIGHT#
#define #NAME#_map_bank #BANK#
#define #NAME#_map_offset #OFFSET#

const unsigned char #NAME#_map[] =
{
#TILES#
};

/* End of #NAME#_map.C */
