/*

 #NAME#_map.H

 Map Include File.

 Info:
   Bank          : #BANK#
   Map size      : #WIDTH# x #HEIGHT#
   Tile offset   : #OFFSET#

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __#NAME#_map_h_INCLUDE
#define __#NAME#_map_h_INCLUDE


#define #NAME#_map_width #WIDTH#
#define #NAME#_map_height #HEIGHT#
#define #NAME#_map_bank #BANK#
#define #NAME#_map_offset #OFFSET#
#define #NAME#_idx #AREA_INDEX#

extern const unsigned char #NAME#_map[];

#endif

/* End of #NAME#_map.H */
