#ifndef __#NAME#_h_INCLUDE
#define __#NAME#_h_INCLUDE

/*

 #NAME#.C

 Tile Source File.

 Info:
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to #TILECOUNT#

 Generated by Manlibear's Aseprite Map Builder

*/

/* Bank of tiles. */
#define #NAME#Bank #BANK#
/* Start of tile array. */

#define #NAME#_length #LENGTH#
#define #NAME#_idx #LAYER_INDEX#
extern const void __bank_#NAME#;
extern const unsigned char #NAME#[];

#endif

/* End of #NAME#.h */