/*

 cerulean_city_map.H

 Map Include File.

 Info:
   Bank          : 4
   Map size      : 80 x 72
   Tile offset   : 103

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __cerulean_city_map_h_INCLUDE
#define __cerulean_city_map_h_INCLUDE


#define cerulean_city_map_width 80
#define cerulean_city_map_height 72
#define cerulean_city_map_bank 4
#define cerulean_city_map_offset 103
#define cerulean_city_idx 10

extern const unsigned char cerulean_city_map[];

#endif

/* End of cerulean_city_map.H */
