/*

 cerulean_city_map.H

 Map Include File.

 Info:
   Bank          : 14
   Map size      : 80 x 72
   Tile offset   : 0

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __cerulean_city_map_h_INCLUDE
#define __cerulean_city_map_h_INCLUDE


#define cerulean_city_map_width 80
#define cerulean_city_map_height 72
#define cerulean_city_map_bank 14
#define cerulean_city_map_offset 0
#define cerulean_city_idx 10

extern const unsigned char cerulean_city_map[];

#endif

/* End of cerulean_city_map.H */
