/*

 oaks_lab_map.H

 Map Include File.

 Info:
   Bank          : 25
   Map size      : 22 x 26
   Tile offset   : 0

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __oaks_lab_map_h_INCLUDE
#define __oaks_lab_map_h_INCLUDE


#define oaks_lab_map_width 22
#define oaks_lab_map_height 26
#define oaks_lab_map_bank 25
#define oaks_lab_map_offset 0
#define oaks_lab_idx 0

extern const unsigned char oaks_lab_map[];

#endif

/* End of oaks_lab_map.H */
