/*



 pallet_town_map.H



 Map Include File.



 Info:

   Bank          : 22

   Map size      : 40 x 36

   Tile offset   : 0



 Generated by Manlibear's Aseprite Map Builder



*/

#ifndef __pallet_town_map_h_INCLUDE

#define __pallet_town_map_h_INCLUDE





#define pallet_town_map_width 40

#define pallet_town_map_height 36

#define pallet_town_map_bank 22

#define pallet_town_map_offset 0

#define pallet_town_idx 5



extern const unsigned char pallet_town_map[];



#endif



/* End of pallet_town_map.H */

