/*

 pallet_town_map.H

 Map Include File.

 Info:
   Bank          : 7
   Map size      : 40 x 36
   Tile offset   : 103

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __pallet_town_map_h_INCLUDE
#define __pallet_town_map_h_INCLUDE


#define pallet_town_map_width 40
#define pallet_town_map_height 36
#define pallet_town_map_bank 7
#define pallet_town_map_offset 103

extern const unsigned char pallet_town_map[];

#endif

/* End of pallet_town_map.H */
