/*

 pewter_city_map.H

 Map Include File.

 Info:
   Bank          : 17
   Map size      : 80 x 72
   Tile offset   : 0

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __pewter_city_map_h_INCLUDE
#define __pewter_city_map_h_INCLUDE


#define pewter_city_map_width 80
#define pewter_city_map_height 72
#define pewter_city_map_bank 17
#define pewter_city_map_offset 0
#define pewter_city_idx 12

extern const unsigned char pewter_city_map[];

#endif

/* End of pewter_city_map.H */
