/*

 pewter_city_map.H

 Map Include File.

 Info:
   Bank          : 5
   Map size      : 80 x 72
   Tile offset   : 103

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __pewter_city_map_h_INCLUDE
#define __pewter_city_map_h_INCLUDE


#define pewter_city_map_width 80
#define pewter_city_map_height 72
#define pewter_city_map_bank 5
#define pewter_city_map_offset 103

extern const unsigned char pewter_city_map[];

#endif

/* End of pewter_city_map.H */
