/*

 players_house_1f_map.H

 Map Include File.

 Info:
   Bank          : 24
   Map size      : 18 x 18
   Tile offset   : 0

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __players_house_1f_map_h_INCLUDE
#define __players_house_1f_map_h_INCLUDE


#define players_house_1f_map_width 18
#define players_house_1f_map_height 18
#define players_house_1f_map_bank 24
#define players_house_1f_map_offset 0
#define players_house_1f_idx 1

extern const unsigned char players_house_1f_map[];

#endif

/* End of players_house_1f_map.H */
