/*

 players_house_1f_map.H

 Map Include File.

 Info:
   Bank          : 9
   Map size      : 18 x 18
   Tile offset   : 103

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __players_house_1f_map_h_INCLUDE
#define __players_house_1f_map_h_INCLUDE


#define players_house_1f_map_width 18
#define players_house_1f_map_height 18
#define players_house_1f_map_bank 9
#define players_house_1f_map_offset 103

extern const unsigned char players_house_1f_map[];

#endif

/* End of players_house_1f_map.H */
