/*

 players_house_gf_map.H

 Map Include File.

 Info:
   Bank          : 23
   Map size      : 18 x 18
   Tile offset   : 0

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __players_house_gf_map_h_INCLUDE
#define __players_house_gf_map_h_INCLUDE


#define players_house_gf_map_width 18
#define players_house_gf_map_height 18
#define players_house_gf_map_bank 23
#define players_house_gf_map_offset 0
#define players_house_gf_idx 3

extern const unsigned char players_house_gf_map[];

#endif

/* End of players_house_gf_map.H */
