/*

 rivals_house_map.H

 Map Include File.

 Info:
   Bank          : 10
   Map size      : 18 x 18
   Tile offset   : 103

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __rivals_house_map_h_INCLUDE
#define __rivals_house_map_h_INCLUDE


#define rivals_house_map_width 18
#define rivals_house_map_height 18
#define rivals_house_map_bank 10
#define rivals_house_map_offset 103
#define rivals_house_idx 2

extern const unsigned char rivals_house_map[];

#endif

/* End of rivals_house_map.H */
