/*

 route_2_map.H

 Map Include File.

 Info:
   Bank          : 6
   Map size      : 40 x 144
   Tile offset   : 103

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __route_2_map_h_INCLUDE
#define __route_2_map_h_INCLUDE


#define route_2_map_width 40
#define route_2_map_height 144
#define route_2_map_bank 6
#define route_2_map_offset 103
#define route_2_idx 8

extern const unsigned char route_2_map[];

#endif

/* End of route_2_map.H */
