/*

 route_9_map.H

 Map Include File.

 Info:
   Bank          : 11
   Map size      : 120 x 36
   Tile offset   : 0

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __route_9_map_h_INCLUDE
#define __route_9_map_h_INCLUDE


#define route_9_map_width 120
#define route_9_map_height 36
#define route_9_map_bank 11
#define route_9_map_offset 0
#define route_9_idx 7

extern const unsigned char route_9_map[];

#endif

/* End of route_9_map.H */
