/*

 route_4_map.H

 Map Include File.

 Info:
   Bank          : 4
   Map size      : 180 x 36
   Tile offset   : 103

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __route_4_map_h_INCLUDE
#define __route_4_map_h_INCLUDE


#define route_4_map_width 180
#define route_4_map_height 36
#define route_4_map_bank 4
#define route_4_map_offset 103
#define route_4_idx 11

extern const unsigned char route_4_map[];

#endif

/* End of route_4_map.H */
