/*

 route_25_map.H

 Map Include File.

 Info:
   Bank          : 1
   Map size      : 120 x 36
   Tile offset   : 103

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __route_25_map_h_INCLUDE
#define __route_25_map_h_INCLUDE


#define route_25_map_width 120
#define route_25_map_height 36
#define route_25_map_length #LENGTH#
#define route_25_map_bank 1
#define route_25_map_offset 103

extern const unsigned char route_25_map[];

#endif

/* End of route_25_map.H */
