/*

 route_22_map.H

 Map Include File.

 Info:
   Bank          : 18
   Map size      : 84 x 40
   Tile offset   : 0

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __route_22_map_h_INCLUDE
#define __route_22_map_h_INCLUDE


#define route_22_map_width 84
#define route_22_map_height 40
#define route_22_map_bank 18
#define route_22_map_offset 0
#define route_22_idx 15

extern const unsigned char route_22_map[];

#endif

/* End of route_22_map.H */
