/*

 route_5_map.H

 Map Include File.

 Info:
   Bank          : 10
   Map size      : 40 x 72
   Tile offset   : 0

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __route_5_map_h_INCLUDE
#define __route_5_map_h_INCLUDE


#define route_5_map_width 40
#define route_5_map_height 72
#define route_5_map_bank 10
#define route_5_map_offset 0
#define route_5_idx 6

extern const unsigned char route_5_map[];

#endif

/* End of route_5_map.H */
