/*

 route_25_map.H

 Map Include File.

 Info:
   Bank          : 12
   Map size      : 120 x 36
   Tile offset   : 0

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __route_25_map_h_INCLUDE
#define __route_25_map_h_INCLUDE


#define route_25_map_width 120
#define route_25_map_height 36
#define route_25_map_bank 12
#define route_25_map_offset 0
#define route_25_idx 16

extern const unsigned char route_25_map[];

#endif

/* End of route_25_map.H */
