/*

 route_3_map.H

 Map Include File.

 Info:
   Bank          : 5
   Map size      : 140 x 36
   Tile offset   : 103

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __route_3_map_h_INCLUDE
#define __route_3_map_h_INCLUDE


#define route_3_map_width 140
#define route_3_map_height 36
#define route_3_map_bank 5
#define route_3_map_offset 103
#define route_3_idx 1

extern const unsigned char route_3_map[];

#endif

/* End of route_3_map.H */
