/*

 route_1_map.H

 Map Include File.

 Info:
   Bank          : 6
   Map size      : 32 x 72
   Tile offset   : 103

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __route_1_map_h_INCLUDE
#define __route_1_map_h_INCLUDE


#define route_1_map_width 32
#define route_1_map_height 72
#define route_1_map_bank 6
#define route_1_map_offset 103
#define route_1_idx 12

extern const unsigned char route_1_map[];

#endif

/* End of route_1_map.H */
