/*

 viridian_city_map.H

 Map Include File.

 Info:
   Bank          : 20
   Map size      : 80 x 72
   Tile offset   : 0

 Generated by Manlibear's Aseprite Map Builder

*/
#ifndef __viridian_city_map_h_INCLUDE
#define __viridian_city_map_h_INCLUDE


#define viridian_city_map_width 80
#define viridian_city_map_height 72
#define viridian_city_map_bank 20
#define viridian_city_map_offset 0
#define viridian_city_idx 4

extern const unsigned char viridian_city_map[];

#endif

/* End of viridian_city_map.H */
